stages:
    - build
    - deploy

variables:
    LC_ALL: "en_US.UTF-8"
    LANG: "en_US.UTF-8"

before_script:
    - bundle install --path ~/.gem

build_android_dev:
    dependencies: []
    stage: build
    variables:
        BUILD_ENVIRONMENT: dev
    artifacts:
        paths:
            - android/app/build/outputs/apk/debug/*.apk
    script:
        - bundle exec fastlane android build_debug
    only:
        - master
    tags:
        - android

